import type { Employee } from "@/components/company-detail/employee-column";
import type { RowData } from "@/components/dashboard/columns";

export const rows: RowData[] = [
  {
    id: "728ed52f",
    company_name: "Acme Corp",
    email: "m@example.com",
    company_address: "123 Main St, New York, NY",
    description: "Leading provider of innovative solutions.",
  },
  {
    id: "489e1d42",
    company_name: "Techify LLC",
    email: "example@gmail.com",
    company_address: "456 Market St, San Francisco, CA",
    description: "Technology solutions for modern businesses.",
  },
  {
    id: "a13fd91b",
    company_name: "Globex Industries",
    email: "john.doe@example.com",
    company_address: "789 Industrial Rd, Chicago, IL",
    description: "Global leader in industrial manufacturing.",
  },
  {
    id: "c82bf71e",
    company_name: "InnoSoft Ltd",
    email: "sara.smith@example.com",
    company_address: "321 Innovation Ave, Austin, TX",
    description: "Innovative software development company.",
  },
  {
    id: "d47ac23a",
    company_name: "NextGen Systems",
    email: "alex.jones@example.com",
    company_address: "654 Future Blvd, Seattle, WA",
    description: "Building next-generation IT systems.",
  },
  {
    id: "f29ed91c",
    company_name: "Visionary Labs",
    email: "linda.williams@example.com",
    company_address: "987 Research Park, Boston, MA",
    description: "Research-driven technology lab.",
  },
  {
    id: "e51cd84b",
    company_name: "Skyline Solutions",
    email: "david.lee@example.com",
    company_address: "159 Skyline Dr, Denver, CO",
    description: "Providing cutting-edge cloud solutions.",
  },
  {
    id: "g62ef12d",
    company_name: "BrightPath Co.",
    email: "emma.brown@example.com",
    company_address: "753 Bright St, Orlando, FL",
    description: "Guiding businesses to brighter futures.",
  },
  {
    id: "h73kd91x",
    company_name: "Pioneer Tech",
    email: "pioneer@example.com",
    company_address: "852 Explorer Rd, Dallas, TX",
    description: "Pioneering innovative tech solutions.",
  },
  {
    id: "i84mf02y",
    company_name: "SummitWorks",
    email: "summit@example.com",
    company_address: "963 Summit Ave, Salt Lake City, UT",
    description: "Helping clients reach their business peak.",
  },
  {
    id: "j95ng13z",
    company_name: "BlueWave Ltd",
    email: "bluewave@example.com",
    company_address: "147 Ocean Dr, Miami, FL",
    description: "Delivering modern IT wave solutions.",
  },
  {
    id: "k06oh24a",
    company_name: "Quantum Systems",
    email: "quantum@example.com",
    company_address: "258 Quantum Rd, Palo Alto, CA",
    description: "Experts in quantum computing solutions.",
  },
  {
    id: "l17pi35b",
    company_name: "Vertex Innovations",
    email: "vertex@example.com",
    company_address: "369 Vertex St, Portland, OR",
    description: "Innovating at the vertex of technology.",
  },
  {
    id: "m28qj46c",
    company_name: "StellarSoft",
    email: "stellar@example.com",
    company_address: "741 Galaxy Blvd, Houston, TX",
    description: "Shining bright in software innovation.",
  },
  {
    id: "n39rk57d",
    company_name: "Nova Enterprises",
    email: "nova@example.com",
    company_address: "852 Nova Ln, Phoenix, AZ",
    description: "Exploring new frontiers in technology.",
  },
  {
    id: "o40sl68e",
    company_name: "Peak Solutions",
    email: "peak@example.com",
    company_address: "963 Peak Rd, Denver, CO",
    description: "Reaching the peak of IT excellence.",
  },
  {
    id: "p51tm79f",
    company_name: "Orbit Global",
    email: "orbit@example.com",
    company_address: "159 Orbit Dr, Los Angeles, CA",
    description: "Global solutions for orbiting success.",
  },
  {
    id: "q62un80g",
    company_name: "Elevate Tech",
    email: "elevate@example.com",
    company_address: "753 Elevation St, San Diego, CA",
    description: "Elevating businesses with technology.",
  },
  {
    id: "r73vo91h",
    company_name: "FusionWorks",
    email: "fusion@example.com",
    company_address: "456 Fusion Ave, Atlanta, GA",
    description: "Fusing ideas into powerful solutions.",
  },
  {
    id: "s84wp02i",
    company_name: "Momentum Inc",
    email: "momentum@example.com",
    company_address: "123 Momentum Blvd, Detroit, MI",
    description: "Keeping businesses moving forward.",
  },
  {
    id: "t95xq13j",
    company_name: "Ignite Solutions",
    email: "ignite@example.com",
    company_address: "321 Ignite St, Austin, TX",
    description: "Igniting growth through innovation.",
  },
  {
    id: "u06yr24k",
    company_name: "Horizon Corp",
    email: "horizon@example.com",
    company_address: "654 Horizon Blvd, Las Vegas, NV",
    description: "Expanding the horizon of possibilities.",
  },
  {
    id: "v17zs35l",
    company_name: "Pulse Technologies",
    email: "pulse@example.com",
    company_address: "987 Pulse Ave, Philadelphia, PA",
    description: "Keeping the pulse of modern tech.",
  },
  {
    id: "w28at46m",
    company_name: "Edge Systems",
    email: "edge@example.com",
    company_address: "159 Edge St, San Jose, CA",
    description: "Delivering solutions at the edge.",
  },
  {
    id: "x39bu57n",
    company_name: "Catalyst Group",
    email: "catalyst@example.com",
    company_address: "753 Catalyst Blvd, Raleigh, NC",
    description: "Catalyzing business transformations.",
  },
  {
    id: "y40cv68o",
    company_name: "Apex Dynamics",
    email: "apex@example.com",
    company_address: "369 Apex Rd, Minneapolis, MN",
    description: "Driving growth through dynamic solutions.",
  },
  {
    id: "z51dw79p",
    company_name: "Nimbus Labs",
    email: "nimbus@example.com",
    company_address: "741 Cloud Ln, Seattle, WA",
    description: "Innovating in the cloud space.",
  },
  {
    id: "aa62ex80q",
    company_name: "Vertex Global",
    email: "vertex.global@example.com",
    company_address: "258 Global St, Boston, MA",
    description: "Global reach with vertex innovation.",
  },
];

export const employees: Employee[] = [
  {
    id: "1",
    name: "John Doe",
    email: "m@example.com",
    password: "password123",
    website: "https://example.com",
    technology: "React, Node.js",
    phone: "+1-123-456-7890",
    role: "CEO",
    designation: "Chief Executive Officer",
    department: "Management",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "example@gmail.com",
    password: "password456",
    website: "https://ui-designs.com",
    technology: "Figma, Tailwind, React",
    phone: "+1-222-333-4444",
    role: "CTO",
    designation: "Chief Technology Officer",
    department: "Technology",
  },
  {
    id: "3",
    name: "Bob Johnson",
    email: "example@example.com",
    password: "password789",
    website: "https://product-mgmt.com",
    technology: "Agile, Scrum, Jira",
    phone: "+1-555-666-7777",
    role: "Product Manager",
    designation: "Senior Product Manager",
    department: "Product",
  },
  {
    id: "4",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    password: "pass123",
    website: "https://emilydavis.dev",
    technology: "React, TypeScript, Express",
    phone: "+1-111-222-3333",
    role: "Employee",
    designation: "Full Stack Developer",
    department: "Engineering",
  },
  {
    id: "5",
    name: "Daniel Lee",
    email: "daniel.lee@example.com",
    password: "pass456",
    website: "https://danlee.io",
    technology: "Node.js, AWS, Docker",
    phone: "+1-444-555-6666",
    role: "Employee",
    designation: "Backend Developer",
    department: "Engineering",
  },
  {
    id: "6",
    name: "Sophia Martinez",
    email: "sophia.m@example.com",
    password: "pass789",
    website: "https://sophiamartinez.com",
    technology: "Vue.js, Nuxt, Tailwind",
    phone: "+1-777-888-9999",
    role: "Employee",
    designation: "Frontend Developer",
    department: "Engineering",
  },
  {
    id: "7",
    name: "William Brown",
    email: "will.b@example.com",
    password: "pass321",
    website: "https://williamb.dev",
    technology: "PostgreSQL, MongoDB, MySQL",
    phone: "+1-222-444-8888",
    role: "Employee",
    designation: "Database Administrator",
    department: "Engineering",
  },
  {
    id: "8",
    name: "Olivia Wilson",
    email: "olivia.w@example.com",
    password: "pass654",
    website: "https://oliviawilson.design",
    technology: "Figma, Adobe XD, Sketch",
    phone: "+1-555-123-4567",
    role: "Employee",
    designation: "UI/UX Designer",
    department: "Design",
  },
  {
    id: "9",
    name: "James Taylor",
    email: "james.t@example.com",
    password: "pass987",
    website: "https://jamestaylor.io",
    technology: "Kubernetes, Jenkins, Terraform",
    phone: "+1-888-999-0000",
    role: "Employee",
    designation: "DevOps Engineer",
    department: "Infrastructure",
  },
  {
    id: "10",
    name: "Ava Anderson",
    email: "ava.a@example.com",
    password: "pass111",
    website: "https://avaanderson.com",
    technology: "Cypress, Jest, Selenium",
    phone: "+1-333-222-1111",
    role: "Employee",
    designation: "QA Engineer",
    department: "Quality Assurance",
  },
  {
    id: "11",
    name: "Michael Thomas",
    email: "michael.t@example.com",
    password: "pass222",
    website: "https://michaelthomas.dev",
    technology: "React, Redux, Next.js",
    phone: "+1-123-321-4567",
    role: "Employee",
    designation: "Frontend Developer",
    department: "Engineering",
  },
  {
    id: "12",
    name: "Isabella Garcia",
    email: "isabella.g@example.com",
    password: "pass333",
    website: "https://isabellagarcia.design",
    technology: "Photoshop, Illustrator, Figma",
    phone: "+1-456-789-1234",
    role: "Employee",
    designation: "Graphic Designer",
    department: "Design",
  },
  {
    id: "13",
    name: "Benjamin Harris",
    email: "ben.h@example.com",
    password: "pass444",
    website: "https://benharris.io",
    technology: "Azure, AWS, GCP",
    phone: "+1-654-321-9876",
    role: "Employee",
    designation: "Cloud Architect",
    department: "Infrastructure",
  },
  {
    id: "14",
    name: "Mia Clark",
    email: "mia.c@example.com",
    password: "pass555",
    website: "https://miaclark.dev",
    technology: "Swift, Kotlin, Flutter",
    phone: "+1-987-654-3210",
    role: "Employee",
    designation: "Mobile Developer",
    department: "Engineering",
  },
  {
    id: "15",
    name: "Ethan Lewis",
    email: "ethan.l@example.com",
    password: "pass666",
    website: "https://ethanlewis.dev",
    technology: "Python, TensorFlow, PyTorch",
    phone: "+1-741-852-9630",
    role: "Employee",
    designation: "Machine Learning Engineer",
    department: "AI/ML",
  },
  {
    id: "16",
    name: "Charlotte Walker",
    email: "charlotte.w@example.com",
    password: "pass777",
    website: "https://charlottewalker.design",
    technology: "Illustrator, Photoshop, Figma",
    phone: "+1-963-852-7410",
    role: "Employee",
    designation: "Brand Designer",
    department: "Design",
  },
  {
    id: "17",
    name: "Alexander King",
    email: "alex.k@example.com",
    password: "pass888",
    website: "https://alexking.dev",
    technology: "SIEM, Firewalls, Pen Testing",
    phone: "+1-852-456-1597",
    role: "Employee",
    designation: "Cybersecurity Analyst",
    department: "Security",
  },
  {
    id: "18",
    name: "Amelia Scott",
    email: "amelia.s@example.com",
    password: "pass999",
    website: "https://ameliascott.design",
    technology: "After Effects, Blender, Premiere",
    phone: "+1-753-951-4563",
    role: "Employee",
    designation: "Motion Designer",
    department: "Design",
  },
  {
    id: "19",
    name: "Lucas Young",
    email: "lucas.y@example.com",
    password: "pass000",
    website: "https://lucasyoung.dev",
    technology: "Next.js, Vercel, Lighthouse",
    phone: "+1-159-357-8520",
    role: "Employee",
    designation: "Performance Engineer",
    department: "Engineering",
  },
  {
    id: "20",
    name: "Harper Allen",
    email: "harper.a@example.com",
    password: "pass101",
    website: "https://harperallen.io",
    technology: "Markdown, Notion, Confluence",
    phone: "+1-258-654-1479",
    role: "Employee",
    designation: "Technical Writer",
    department: "Documentation",
  },
  {
    id: "21",
    name: "Henry Hall",
    email: "henry.h@example.com",
    password: "pass202",
    website: "https://henryhall.dev",
    technology: "Angular, TypeScript, RxJS",
    phone: "+1-369-258-1470",
    role: "Employee",
    designation: "Frontend Developer",
    department: "Engineering",
  },
  {
    id: "22",
    name: "Evelyn Green",
    email: "evelyn.g@example.com",
    password: "pass303",
    website: "https://evelyngreen.com",
    technology: "SEO, Google Ads, Analytics",
    phone: "+1-951-753-4567",
    role: "Employee",
    designation: "SEO Specialist",
    department: "Marketing",
  },
  {
    id: "23",
    name: "Jack Adams",
    email: "jack.a@example.com",
    password: "pass404",
    website: "https://jackadams.dev",
    technology: "Java, Spring Boot, Hibernate",
    phone: "+1-852-159-3570",
    role: "Employee",
    designation: "Java Developer",
    department: "Engineering",
  },
];
